### A CI workflow template that runs linting and python testing
### TODO: Modify as needed or as desired.

name: Test tap-openweathermap

on:
  push:
    branches: [master]
    paths-ignore: [README.md]

  # be careful with this as it allows secret access for fork PR workflow runs
  # ensure "Require approval for all external contributors" is enabled and PR does not
  # contain any malicious workflow additions/changes
  pull_request_target:
    paths-ignore: [README.md]

  schedule:
  - cron: 0 9 * * *

jobs:
  pytest:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      TAP_OPENWEATHERMAP_API_KEY: ${{secrets.TAP_OPENWEATHERMAP_API_KEY}}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
    steps:
    - uses: actions/checkout@v5
      with:
        ref: ${{ github.event_name == 'pull_request_target' && github.event.pull_request.head.sha || github.sha }}
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Poetry
      run: |
        pip install poetry
    - name: Install dependencies
      run: |
        poetry env use ${{ matrix.python-version }}
        poetry install
    - name: Test with pytest
      run: |
        poetry run pytest
